### ISSUE TITLE
Final Report

### ISSUE THREAD

**Issue by RichardVas** [Teaching-projects/SZE-MOSZE-2021-Caffeine#8]
@hegyhati Tisztelt Tanár Úr! Elkészültünk a féléves feladat megvalósításával, kérjük értékelje.

**Comment by hegyhati** [comment]
@RichardVas 5
@matevarga96  4
Parhuzamos branchek nem nagyon voltak, de ettol eltekintve szep munka, vallveregetes. Jo nyarat!
